### ISSUE TITLE
ubuntu 启动配置

### ISSUE THREAD

**Issue by yiyern** [yiyern/yiyern.github.io#55]
```
vim /etc/netplan/50-cloud-init.yaml 
```
配置如下：
```
network:
    ethernets:
        enp4s0:
            addresses: [192.168.0.20/24]  //IP址
            gateway4: 192.168.0.1  // 网关
            nameservers:
             addresses: [114.114.114.114, 192.168.0.1] //DNS
            dhcp4: no
            optional: no
    version: 2
```
